### ISSUE TITLE
Holding a button while opening a RLC will replace the contents of the RLC even if its still running(i.e. editing disabled)

### ISSUE THREAD

**Issue by Shinchai** [stfwi/redstonepen#40] opened 2024-03-18 05:53 UTC
By button, I refer to alphanumeric keys.

Even if the logic circuit is running, it will type once (replacing everything) and then ignore the rest of the inputs.

Also, the caret is too dark against the background of the editor. It would be better if it were white or inverted against its background (similar to windows inverted cursor)

**Comment by stfwi** [comment] 2024-03-18 20:13
Hi shinchai, ty for the hint, you're like with the last issue on fabric 1.20.4, pen version >=1.8.28?

**Comment by stfwi** [comment] 2024-03-18 21:41
Aye, the editor field was unlocked until the code arrived from the server side, easy fix ;). Used the occasion to make the cursor brighter, too.

**Comment by Shinchai** [comment] 2024-03-19 04:48
I'm using v1.8.29.

_P.S. if you have an interest in modding about, I have come up with an idea for lore-friendly quick-build system that I'm eager to share with a modder._

**Comment by stfwi** [comment] 2024-03-19 18:20
Hi, thanks for addressing me there. Unfortunately, I do not have much time for my modding hobby and would not be able to maintain more mods. But again, thank you for asking.

**Comment by stfwi** [comment] 2024-03-23 01:08
Oky, the fixes are pushed to curse and modrinth for fabric and neo 1.20.4, I'll close this one. Could you risk a glimpse if the issue is gone and reopen if not? Cheer's,-

**Closed by stfwi** 2024-03-23 01:08 UTC
Labels: anomaly, fixed, scheduled, mc1.20

**Comment by Shinchai** [comment] 2024-03-23 14:12
yep, its fixed. danke
