### ISSUE TITLE
Issue #30 on 1.20.2-1.6.24

### ISSUE THREAD

**Issue by oknacupZero** [stfwi/redstonepen#36] opened 2024-02-16 07:06 UTC
"Internal Exception: `io.netty.handler.codec.DecoderException:` `java.lang.IllegalArgumentException:` Unknown recipe serializer minecraft:nether_wart_block"
Happened on joining dedicated server.

**Comment by stfwi** [comment] 2024-02-16 19:42
Hi, let me take a look at this, this looks like 1.20.1 build config used in 1.20.2. It also gives me a reason to make a back-port fix for the previous issue ;) Cheers;

**Comment by stfwi** [comment] 2024-02-17 10:25
Hi, same for this issue, could you take a look if the issue is also resolved in your setup? Cheers;

**Comment by oknacupZero** [comment] 2024-02-17 11:32
Can join with no issues.

**Comment by nuypham** [comment] 2024-02-17 16:55
Nice! Thank you, Also Fixed issue Internal Exception recipe from Croptopia mod when joining the server.

**Comment by stfwi** [comment] 2024-02-20 22:35
Oky very nice, thanks for the feedback; Cheers,-

**Closed by stfwi** 2024-02-20 22:35 UTC
Labels: anomaly, approval-pending, mc1.20, back-port
